version: '2'
services:
    demo-das-dn-app:
        image: demo-das-dn
        external_links:
            - demo-das-dn-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/demo-das-dn
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    demo-das-dn-postgresql:
        extends:
            file: postgresql.yml
            service: demo-das-dn-postgresql
